CREATE TABLE `modules`.`module_account` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` int(11) NOT NULL,
  `MODULE_ID` int(11) NOT NULL,
  `EXPIRY_DATE` date DEFAULT NULL,
  `ACTIVATION_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `MODULE_ACCOUNT_ASSOCIATION` (`MODULE_ID`,`ACCOUNT_ID`),
  KEY `ACCOUNT_TABLE_idx` (`ACCOUNT_ID`),
  CONSTRAINT `MODULE_TABLE` FOREIGN KEY (`MODULE_ID`) REFERENCES `modules` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ACCOUNT_TABLE` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `cms`.`account` (`ACCOUNT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;