

CREATE TABLE IF NOT EXISTS `group_member` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GROUP_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_GROUP_MEMBERS1` (`USER_ID`,`GROUP_ID`),
  KEY `FK_GRP_ACCN` (`GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

ALTER TABLE `group_member`
  ADD CONSTRAINT `FK_GRP_ACCN` FOREIGN KEY (`GROUP_ID`) REFERENCES `group` (`GROUP_ID`),
  ADD CONSTRAINT `FK_USR_ACCN` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`);


