

CREATE TABLE IF NOT EXISTS `permission` (
  `PERMISSION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int(11) NOT NULL,
  `ENTITY_OPERATION_ID` int(11) NOT NULL,
  PRIMARY KEY (`PERMISSION_ID`),
  UNIQUE KEY `UK_ROLE_PERMISSION` (`ENTITY_ID`,`ENTITY_OPERATION_ID`),
  KEY `FK_PERMISSION_ENTITYOPERATION` (`ENTITY_OPERATION_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;




INSERT INTO `permission` (`PERMISSION_ID`, `ENTITY_ID`, `ENTITY_OPERATION_ID`) VALUES
(1, 3, 2),
(3, 3, 3);
 ALTER TABLE `permission`
  ADD CONSTRAINT `FK_PERMISSION_ENTITY` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`),
  ADD CONSTRAINT `FK_PERMISSION_ENTITYOPERATION` FOREIGN KEY (`ENTITY_OPERATION_ID`) REFERENCES `entity_operation` (`ENTITY_OPERATION_ID`);