use cms;
INSERT INTO SITE_DOMAIN (DOMAIN_NAME,SITE_ID) VALUES ("www.market.org",3);
INSERT INTO SITE_DOMAIN (DOMAIN_NAME,SITE_ID) VALUES ("www.contento.com",4);
INSERT INTO SITE_DOMAIN (DOMAIN_NAME,SITE_ID) VALUES ("www.baazaar.com",3);
INSERT INTO SITE_DOMAIN (DOMAIN_NAME,SITE_ID) VALUES ("www.baazaar.pk",3);
