INSERT INTO CATEGORY VALUES (1,"Sports",null);
INSERT INTO CATEGORY VALUES (2,"News",null);
INSERT INTO CATEGORY VALUES (3,"Education",null);
INSERT INTO CATEGORY VALUES (4,"Tennis",1);
INSERT INTO CATEGORY VALUES (5,"Cricket",1);