/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Hammad Afridi
 * Created : 10/15/2011
 */

package com.contento3.cms.content.service.impl;
import com.contento3.cms.content.dao.ContentDao;
import com.contento3.cms.content.service.ContentService;



public class ContentServiceImpl implements ContentService {

	private ContentDao contentDao;

	
}
