/*
-- Query: select * from page_section_type
-- Date: 2012-08-11 23:39
*/
INSERT INTO `PAGE_SECTION_TYPE` (`PAGE_SECTION_TYPE_ID`,`PAGE_SECTION_TYPE_NAME`,`DESCRIPTION`) VALUES (1,'HEADER','Page header');
INSERT INTO `PAGE_SECTION_TYPE` (`PAGE_SECTION_TYPE_ID`,`PAGE_SECTION_TYPE_NAME`,`DESCRIPTION`) VALUES (2,'FOOTER','Page footer');
INSERT INTO `PAGE_SECTION_TYPE` (`PAGE_SECTION_TYPE_ID`,`PAGE_SECTION_TYPE_NAME`,`DESCRIPTION`) VALUES (3,'BODY','Page body');
INSERT INTO `PAGE_SECTION_TYPE` (`PAGE_SECTION_TYPE_ID`,`PAGE_SECTION_TYPE_NAME`,`DESCRIPTION`) VALUES (4,'LEFT_NAVIGATION','Page left navigation');
INSERT INTO `PAGE_SECTION_TYPE` (`PAGE_SECTION_TYPE_ID`,`PAGE_SECTION_TYPE_NAME`,`DESCRIPTION`) VALUES (5,'RIGHT_NAVIGATION','Page right navigation');
INSERT INTO `PAGE_SECTION_TYPE` (`PAGE_SECTION_TYPE_ID`,`PAGE_SECTION_TYPE_NAME`,`DESCRIPTION`) VALUES (6,'METATAGS','page meta tag');
INSERT INTO `PAGE_SECTION_TYPE` (`PAGE_SECTION_TYPE_ID`,`PAGE_SECTION_TYPE_NAME`,`DESCRIPTION`) VALUES (7,'CUSTOM','Custom page');
