USE CMS;
ALTER TABLE CATEGORY CHANGE PARENT_CATEGORY_ID PARENT_CATEGORY_ID INT(11);
ALTER TABLE CATEGORY MODIFY CATEGORY_NAME VARCHAR(45) NOT NULL;
ALTER TABLE CATEGORY  ADD CONSTRAINT `FK_PARENT` FOREIGN KEY (`PARENT_CATEGORY_ID`) REFERENCES `CATEGORY`  (`CATEGORY_ID`);