USE CRM;

-- ADDING NEW COLUNM TO  USER TABLE
ALTER  TABLE  USERS 
ADD  ACCOUNT_ID INT(11);

 -- SETTING FOREIGN KEY 
 ALTER  TABLE  USERS 
 ADD FOREIGN KEY (ACCOUNT_ID)
 REFERENCES CMS.ACCOUNT(ACCOUNT_ID) ;
 
 -- ALTER TALE TO ADD NOT NULL PROPERTY
 ALTER  TABLE  USERS 
MODIFY  ACCOUNT_ID INT(11) NOT NULL;