

CREATE TABLE `CATEGORY` (
  `CATEGORYID` int(11) NOT NULL,
  `CATEGORY_NAME` varchar(45) DEFAULT NULL,
  `PARENT_CATEGORY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CATEGORYID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

