
CREATE TABLE `CMS`.`CATEGORY` (
  `CATEGORY` int(11) NOT NULL,
  `CATEGORY` varchar(45) DEFAULT NULL,
  `PARENT_CATEGORY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CATEGORYID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

