alter table CATEGORY change CATEGORYID CATEGORY_ID int(11);
alter table CATEGORY change PARENT_CATEGORY PARENT_CATEGORY_ID int(11);
ALTER TABLE CATEGORY Modify CATEGORY_NAME varchar(45) NOT NULL;
ALTER TABLE CATEGORY  ADD CONSTRAINT `FK_PARENT` FOREIGN KEY (`PARENT_CATEGORY_ID`) REFERENCES `CATEGORY`  (`CATEGORY_ID`)