SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `cms` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
SHOW WARNINGS;
USE `cms`;

-- -----------------------------------------------------
-- Table `cms`.`PAGE_LAYOUT_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`PAGE_LAYOUT_TYPE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `cms`.`PAGE_LAYOUT_TYPE` (
  `PAGE_LAYOUT_TYPE_ID` INT NOT NULL ,
  `PAGE_LAYOUT_TYPE_NAME` VARCHAR(45) NOT NULL ,
  `DESCRIPTION` VARCHAR(500) NOT NULL ,
  PRIMARY KEY (`PAGE_LAYOUT_TYPE_ID`) )
ENGINE = InnoDB
COMMENT = 'Used to specify different type of page layout from which the site user can choose. for e.g. Libray Layout,Custom Layout,Build Layout.';

SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
