ALTER TABLE CMS.CATEGORY CHANGE CATEGORY_ID CATEGORY_ID INT AUTO_INCREMENT; 
ALTER TABLE CMS.CATEGORY ADD COLUMN `ACCOUNT_ID` INT(11) NOT NULL;
ALTER TABLE CMS.CATEGORY ADD FOREIGN KEY  (`ACCOUNT_ID`) REFERENCES `CMS`.`ACCOUNT`(`ACCOUNT_ID`);

 