use CMS;

-- DOCUMENT TABLE
-- Holds the data for entities of type Document

DROP TABLE IF EXISTS DOCUMENT;

CREATE TABLE DOCUMENT (
DOCUMENT_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DOCUMENT_UUID VARCHAR(75) UNIQUE KEY,
DOCUMENT_TITLE VARCHAR(128) NOT NULL,
DOCUMENT_TYPE_ID INTEGER NOT NULL,
URL VARCHAR(500),
STORAGE_TYPE_ID INTEGER NOT NULL,
DOCUMENT_CONTENT BLOB,
ACCOUNT_ID INTEGER NOT NULL,
CONSTRAINT FK_DOC_STRGTYPE FOREIGN KEY(STORAGE_TYPE_ID) REFERENCES STORAGE_TYPE(STORAGE_ID),
CONSTRAINT FK_DOC_ACCNT FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
CONSTRAINT FK_DOC_DOCTYPE FOREIGN KEY(DOCUMENT_TYPE_ID) REFERENCES DOCUMENT_TYPE(DOCUMENT_TYPE_ID)
);