ALTER TABLE CMS.ACCOUNT
ADD COLUMN ACCOUNT_TYPE_ID INT(11) NOT NULL DEFAULT 1;

INSERT INTO MODULES.ACCOUNT_TYPE VALUES(1,'CUSTOM','CUSTOM');

ALTER TABLE CMS.ACCOUNT
ADD FOREIGN KEY FK_ACCOUNT_ACCOUNT_TYPE (ACCOUNT_TYPE_ID)
REFERENCES MODULES.ACCOUNT_TYPE(ACCOUNT_TYPE_ID);