-- ADDING NEW COLUNM `LIBRARY_ID`
ALTER TABLE `CMS`.`DOCUMENT` 
ADD COLUMN `LIBRARY_ID` INT(11) NOT NULL DEFAULT 1, 
ADD CONSTRAINT `FK_CONTENT_LIBRARY_TABLE_LIBRARY_ID` FOREIGN KEY (`LIBRARY_ID`) 
REFERENCES `CMS`.`CONTENT_LIBRARY`(`LIBRARY_ID`);