ALTER TABLE IMAGE DROP COLUMN IMAGE_UUIID;
ALTER TABLE IMAGE ADD IMAGE_ID INT NOT NULL PRIMARY KEY  AUTO_INCREMENT;
ALTER TABLE IMAGE ADD IMAGE_UUID VARCHAR(75) NOT NULL UNIQUE AFTER IMAGE_ID;

DROP TABLE  IF EXISTS SITE_IMAGE ;
CREATE TABLE  SITE_IMAGE  (
    SITE_ID INT(11) NOT NULL,
    IMAGE_ID INT(11)  NOT NULL,
    PRIMARY KEY (SITE_ID,IMAGE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;