/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Hammad Afridi
 * Created : 10/15/2011
 */

package com.olive.cms.content.dao;

import com.olive.cms.content.model.Content;
import com.olive.common.dao.GenericDao;

public interface ContentDao extends GenericDao<Content,Integer> {
	
}
