ALTER TABLE `cms`.`site` ADD COLUMN `DEFAULT_PAGE_ID` INT(11) NULL  AFTER `LANGUAGE` , 
  ADD CONSTRAINT `SITE_DEFAULT_PAGE_ID`
  FOREIGN KEY (`DEFAULT_PAGE_ID` )
  REFERENCES `cms`.`page` (`PAGE_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `SITE_DEFAULT_PAGE_ID_idx` (`DEFAULT_PAGE_ID` ASC) ;
