CREATE  TABLE `storage_infrastructure`.`AWSS3` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `END_POINT` VARCHAR(1000) NOT NULL ,
  `BUCKET_NAME` VARCHAR(500) NULL ,
  `SECRET_KEY` VARCHAR(250) NOT NULL ,
  `ACCESS_KEY` VARCHAR(250) NOT NULL ,
  `ACCOUNT_ID` INT NOT NULL ,
  CONSTRAINT FK_ACC_STRGINFRA FOREIGN KEY(ACCOUNT_ID) REFERENCES CMS.ACCOUNT(ACCOUNT_ID),
  PRIMARY KEY (`ID`) );