ALTER TABLE `cms`.`template` ADD COLUMN `TEMPLATE_CATEGORY_ID` INT NULL  AFTER `ACCOUNT_ID` , 
  ADD CONSTRAINT `FK_TEMPLATE_TMPLT_CATEGORY`
  FOREIGN KEY (`TEMPLATE_CATEGORY_ID` )
  REFERENCES `cms`.`template_categories` (`TEMPLATE_CATEGORY_ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_TEMPLATE_TMPLT_CATEGORY_idx` (`TEMPLATE_CATEGORY_ID` ASC);