delimiter $$

CREATE TABLE `template_categories` (
  `TEMPLATE_CATEGORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEMPLATE_CATEGORY_NAME` varchar(250) NOT NULL,
  `TEMPLATE_CATEGORY_DESCRIPTION` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`TEMPLATE_CATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1$$

