CREATE  TABLE `module_email_marketing`.`newsletter_subscription` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NEWSLETTER_ID` INT(11) NOT NULL ,
  `SUBSCRIPTION_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_MAPPING_SUBSCTION_idx` (`SUBSCRIPTION_ID` ASC) ,
  INDEX `FK_MAPPING_NEWSLETTER_idx` (`NEWSLETTER_ID` ASC) ,
  CONSTRAINT `FK_MAPPING_SUBSCTION`
    FOREIGN KEY (`SUBSCRIPTION_ID` )
    REFERENCES `module_email_marketing`.`subscription` (`SUBSCRIPTION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MAPPING_NEWSLETTER`
    FOREIGN KEY (`NEWSLETTER_ID` )
    REFERENCES `module_email_marketing`.`newsletter` (`NEWSLETTER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
