
CREATE TABLE `SUBSCRIPTION` (
  `SUBSCRIPTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUBSCRIPTION_NAME` varchar(250) NOT NULL,
  `DESCRIPTION` varchar(5000) DEFAULT NULL,
  `ACCOUNT_ID` int(11) NOT NULL,
  `CREATED_ON` date DEFAULT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`SUBSCRIPTION_ID`),
  KEY `FK_SUBSCRIPTION_CREATEDUSER` (`USER_ID`),
  KEY `FK_SUBSCRIPTION_ACCOUNT` (`ACCOUNT_ID`),
  CONSTRAINT `FK_SUBSCRIPTION_ACCOUNT` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `cms`.`account` (`ACCOUNT_ID`),
  CONSTRAINT `FK_SUBSCRIPTION_CREATEDUSER` FOREIGN KEY (`USER_ID`) REFERENCES `platform_users`.`user` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

