CREATE TABLE `NEWSLETTER` (
  `NEWSLETTER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NEWSLETTER_NAME` varchar(1000) NOT NULL,
  `STATUS` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(5000) DEFAULT NULL,
  `TEMPLATE_ID` int(11) NOT NULL,
  `SUBJECT` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`NEWSLETTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

ALTER TABLE `module_email_marketing`.`newsletter` ADD COLUMN `ACCOUNT_ID` INT(11) NOT NULL  AFTER `SUBJECT` ;

ALTER TABLE NEWSLETTER
  ADD CONSTRAINT `FK_NEWSLETTER_ACCOUNT`
    FOREIGN KEY (`ACCOUNT_ID` )
    REFERENCES `cms`.`account` (`ACCOUNT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
