CREATE  TABLE `module_email_marketing`.`SUBSCRIBER` (
  `SUBSCRIBER_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `EMAIL` VARCHAR(150) NOT NULL ,
  `FIRST_NAME` VARCHAR(150) NULL ,
  `LAST_NAME` VARCHAR(150) NULL ,
  `SITE_USER_ID` INT(11) NULL ,
  `SITE_ID` INT(11) NULL ,
  `SUBSCRIPTION_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`SUBSCRIBER_ID`) ,
  INDEX `FK_SUSCRIBER_SUBSCRIPTION_idx` (`SUBSCRIPTION_ID` ASC) ,
  CONSTRAINT `FK_SUSCRIBER_SUBSCRIPTION`
    FOREIGN KEY (`SUBSCRIPTION_ID` )
    REFERENCES `module_email_marketing`.`subscription` (`SUBSCRIPTION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
