/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Hammad Afridi
 * Created : 10/15/2011
 */

package com.olive.cms.content.service.impl;
import com.olive.cms.content.service.ContentService;
import com.olive.cms.content.dao.ContentDao;



public class ContentServiceImpl implements ContentService {

	private ContentDao contentDao;

	
}
