INSERT INTO ASSOCIATED_CONTENT_SCOPE VALUES(1,"SCOPE 1"," TYPE 1");
INSERT INTO ASSOCIATED_CONTENT_SCOPE VALUES(2,"SCOPE 2"," TYPE 2");
INSERT INTO ASSOCIATED_CONTENT_SCOPE VALUES(3,"SCOPE 3"," TYPE 3");