ALTER TABLE ARTICLE  CHANGE ARTICLE_UUID  ARTICLE_ID 
INT NOT NULL AUTO_INCREMENT;

ALTER TABLE ARTICLE ADD ARTICLE_UUID VARCHAR(45) NOT NULL AFTER ARTICLE_ID;
ALTER TABLE ARTICLE ADD UNIQUE (ARTICLE_UUID);

ALTER TABLE ARTICLE  MODIFY DATE_CREATED  DATE;
ALTER TABLE ARTICLE  MODIFY DATE_POSTED  DATE;
ALTER TABLE ARTICLE MODIFY BODY LONGTEXT;

ALTER TABLE ARTICLE ADD  LAST_UPDATED DATE AFTER DATE_POSTED;
ALTER TABLE ARTICLE ADD  EXPIRY_DATE DATE AFTER LAST_UPDATED;