Alter table ARTICLE  change ARTICLE_UUID  ARTICLE_ID 
INT NOT NULL AUTO_INCREMENT;

ALTER TABLE ARTICLE ADD ARTICLE_UUID varchar(45) not null AFTER ARTICLE_ID;
alter table ARTICLE add unique (ARTICLE_UUID);

Alter table ARTICLE  Modify DATE_CREATED  date;
Alter table ARTICLE  Modify DATE_POSTED  date;
Alter table ARTICLE Modify body LONGTEXT;

ALTER TABLE ARTICLE ADD  LAST_UPDATED DATE AFTER DATE_POSTED;
ALTER TABLE ARTICLE ADD  EXPIRY_DATE DATE AFTER LAST_UPDATED;