INSERT INTO PLATFORM_USERS.ROLE VALUES(1,'ROLE_ARTICLE_MANAGER','All operations related to ARTICLE',1);	
INSERT INTO PLATFORM_USERS.ROLE VALUES(2,'ROLE_IMAGE_MANAGER','All operations related to IMAGE',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(3,'ROLE_CONTENT_LIBRARY_MANAGER','All operations related to CONTENT LIBRARY',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(4,'ROLE_DOCUMENT_MANAGER','All operations related to DOCUMENT',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(5,'ROLE_TEMPLATE_MANAGER','All operations related to TEMPLATE',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(6,'ROLE_TEMPLATE_LIBRARY_MANAGER','All operations related to TEMPLATE LIBRARY',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(7,'ROLE_SITE_CONFIG_MANAGER','All operations related to SITE CONFIG',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(8,'ROLE_SITE_CONTENT_MANAGER','All operations related to SITE CONTENT',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(9,'ROLE_SITE_MANAGER','All operations related to SITE',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(10,'ROLE_PAGE_MANAGER','All operations related to PAGE',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(11,'ROLE_USER_MANAGER','All operations related to USER',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(12,'ROLE_GROUP_MANAGER','All operations related to GROUP',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(13,'ROLE_PERMISSION_MANAGER','All operations related to PERMISSION',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(14,'ROLE_ROLE_MANAGER','All operations related to ROLE',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(15,'ROLE_USER_ACCOUNT_MANAGER','All operations related to USER ACCOUNT',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(16,'ROLE_CATEGORY_MANAGER','All operations related to CATEGORY',1);
INSERT INTO PLATFORM_USERS.ROLE VALUES(17,'ROLE_ACCOUNT_MANAGER','All operations related to ACCOUNT',1);








