INSERT INTO PLATFORM_USERS.GROUP VALUES(1,'Content Manager','Content Manager',1);
INSERT INTO PLATFORM_USERS.GROUP VALUES(2,'Designer','Designer',1);
INSERT INTO PLATFORM_USERS.GROUP VALUES(3,'Site Manager','Site Manager',1);
INSERT INTO PLATFORM_USERS.GROUP VALUES(4,'Security Manager','Security Manager',1);
INSERT INTO PLATFORM_USERS.GROUP VALUES(5,'Super Admin','Super Admin',1);
INSERT INTO PLATFORM_USERS.GROUP VALUES(6,'Admin','Admin',1);