USE CMS;

CREATE TABLE ARTICLE_IMAGE_ASSOCIATION (
ARTICLE_ID INT(11) NOT NULL,
IMAGE_ID INT(11) NOT NULL,
ASSOCIATED_CONTENT_SCOPE INT(11) NOT NULL,
ACCOUNT_ID INT(11),
CONSTRAINT FK_ARTICLE_ARTLIMAGEASSOC
FOREIGN KEY (ARTICLE_ID) 
REFERENCES ARTICLE(ARTICLE_ID),
CONSTRAINT FK_IMAGE_ARTLIMAGEASSOC 
FOREIGN KEY (IMAGE_ID)  
REFERENCES IMAGE(IMAGE_ID),
CONSTRAINT FK_CONT_SCOPE_ARTLIMAGEASSOC 
FOREIGN KEY (ASSOCIATED_CONTENT_SCOPE)  
REFERENCES ASSOCIATED_CONTENT_SCOPE(ID),
CONSTRAINT FK_ACCOUNT_ARTLIMAGEASSOC 
FOREIGN KEY (ACCOUNT_ID)  
REFERENCES ACCOUNT(ACCOUNT_ID),
PRIMARY KEY(ARTICLE_ID,IMAGE_ID,ASSOCIATED_CONTENT_SCOPE)
);