create schema CRM;

USE CRM

CREATE  TABLE IF NOT EXISTS `CRM`.`USERS`
(  `ID` INT NOT NULL AUTO_INCREMENT ,
`USERNAME` VARCHAR(20) NOT NULL ,
`PASSWORD` VARCHAR(150) NOT NULL ,
`PASSWORD_REMINDER` VARCHAR(45) NOT NULL ,
`IS_ENABLED` BINARY NOT NULL DEFAULT 1 ,
`SITE_ID` INT NOT NULL ,
`UUID` VARCHAR(45) NOT NULL ,
`IS_EMAIL_USERNAME` BINARY NOT NULL DEFAULT 0 ,
PRIMARY KEY (`ID`) ,
INDEX `FK_SITE_USER` (`SITE_ID` ASC) ,
UNIQUE INDEX `UNIQUE_INDEX_UUID` (`UUID` ASC) ,
INDEX `UNIQUE_INDEX_USERNAME` (`USERNAME` ASC) ,
CONSTRAINT `FK_SITE_USER`
FOREIGN KEY (`SITE_ID` )
REFERENCES `CMS`.`SITE` (`SITE_ID` )
ON DELETE NO ACTION
ON UPDATE NO ACTION)ENGINE = InnoDB COMMENT = 'Consists of registered site users.' ;