<<<<<<< HEAD
function com_contento3_web_widgetset_CmsadminWidgetset(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',Vb='.cache.html',$='/',Ob='09B3641B1FCF8894FACF9CFD5DF841E4',Pb='2E717C71E6A89F2D986393419E904753',Qb='329F7F9F4585C862D1154EFB443B855D',Rb='90C5FA24CBC77EAAC87E6B70A349F0D8',Ub=':',nb='::',$b='<script defer="defer">com_contento3_web_widgetset_CmsadminWidgetset.onInjectionDone(\'com.contento3.web.widgetset.CmsadminWidgetset\')<\/script>',gb='<script id="',Yb='<script language="javascript" src="',qb='=',Z='?',sb='Bad handler "',Sb='C811017FEEB2C24B62674B9832D7B5DD',Tb='CFA0BF2A7DAE67D426558E4C1F4893B1',Wb='DOMContentLoaded',ib='SCRIPT',fb='__gwt_marker_com.contento3.web.widgetset.CmsadminWidgetset',jb='base',bb='baseUrl',S='begin',R='bootstrap',Xb='ckeditor/ckeditor.js',Zb='ckeditor/ckeditor.js"><\/script>',ab='clear.cache.gif',P='com.contento3.web.widgetset.CmsadminWidgetset',db='com.contento3.web.widgetset.CmsadminWidgetset.nocache.js',mb='com.contento3.web.widgetset.CmsadminWidgetset::',pb='content',X='end',Ib='gecko',Jb='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',Mb='hosted.html?com_contento3_web_widgetset_CmsadminWidgetset',Hb='ie6',Gb='ie8',Fb='ie9',wb='iframe',_='img',xb="javascript:''",Lb='loadExternalRefs',kb='meta',zb='moduleRequested',W='moduleStartup',Eb='msie',lb='name',Bb='opera',yb='position:absolute;width:0;height:0;border:none',Db='safari',cb='script',Nb='selectingPermutation',Q='startup',eb='undefined',Kb='unknown',Ab='user.agent',Cb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}com_contento3_web_widgetset_CmsadminWidgetset=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Bb)!=-1}())return Bb;if(function(){return b.indexOf(Cb)!=-1}())return Db;if(function(){return b.indexOf(Eb)!=-1&&m.documentMode>=9}())return Fb;if(function(){return b.indexOf(Eb)!=-1&&m.documentMode>=8}())return Gb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Hb;if(function(){return b.indexOf(Ib)!=-1}())return Jb;return Kb};u[Ab]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};com_contento3_web_widgetset_CmsadminWidgetset.onScriptLoad=function(){if(H){q=true;B()}};com_contento3_web_widgetset_CmsadminWidgetset.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Lb,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Mb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Nb});if(!A()){try{F([Bb],Ob);F([Gb],Pb);F([Db],Qb);F([Jb],Rb);F([Hb],Sb);F([Fb],Tb);J=w[G(Ab)];var L=J.indexOf(Ub);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+Vb}catch(a){return}}var M;function N(){if(!r){r=true;B();if(m.removeEventListener){m.removeEventListener(Wb,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(Wb,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Lb,millis:(new Date).getTime(),type:S});if(!__gwt_scriptsLoaded[Xb]){__gwt_scriptsLoaded[Xb]=true;document.write(Yb+s+Zb)}m.write($b)}
com_contento3_web_widgetset_CmsadminWidgetset();
=======
function com_contento3_web_widgetset_CmsadminWidgetset(){var U='',R=' top: -1000px;',pb='" for "gwt:onLoadErrorFn"',nb='" for "gwt:onPropertyErrorFn"',$='");',qb='#',Ub='.cache.js',sb='/',yb='//',Nb='0BA6055FA1C995FEA0DE5C383169D74F',Ob='4060CDC893E08D15F7CD6DB286D5193D',Pb='7EFE2BA8DEFD83EA89E1F2CA11C62086',Qb='99B64B3892D316802429792AD1BC3093',Tb=':',hb='::',T='<!doctype html>',V='<html><head><\/head><body><\/body><\/html>',kb='=',rb='?',Rb='A177C0883A4340BF21D59DD22822E527',mb='Bad handler "',S='CSS1Compat',Y='Chrome',X='DOMContentLoaded',M='DUMMY',Sb='EE6FF81688EDD16022493D4D6B7A2D13',xb='base',vb='baseUrl',H='begin',N='body',G='bootstrap',ub='clear.cache.gif',K='com.contento3.web.widgetset.CmsadminWidgetset',Mb='com.contento3.web.widgetset.CmsadminWidgetset.devmode.js',wb='com.contento3.web.widgetset.CmsadminWidgetset.nocache.js',gb='com.contento3.web.widgetset.CmsadminWidgetset::',jb='content',Wb='end',Z='eval("',Ib='gecko',Jb='gecko1_8',I='gwt.codesvr.com.contento3.web.widgetset.CmsadminWidgetset=',J='gwt.codesvr=',ob='gwt:onLoadErrorFn',lb='gwt:onPropertyErrorFn',ib='gwt:property',db='head',Eb='ie10',Hb='ie6',Gb='ie8',Fb='ie9',O='iframe',tb='img',ab='javascript',P='javascript:""',Vb='loadExternalRefs',eb='meta',cb='moduleRequested',bb='moduleStartup',Db='msie',fb='name',Ab='opera',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Cb='safari',_='script',Lb='selectingPermutation',L='startup',W='undefined',Kb='unknown',zb='user.agent',Bb='webkit';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_contento3_web_widgetset_CmsadminWidgetset.__sendStats=r;com_contento3_web_widgetset_CmsadminWidgetset.__moduleName=K;com_contento3_web_widgetset_CmsadminWidgetset.__errFn=null;com_contento3_web_widgetset_CmsadminWidgetset.__moduleBase=M;com_contento3_web_widgetset_CmsadminWidgetset.__softPermutationId=0;com_contento3_web_widgetset_CmsadminWidgetset.__computePropValue=null;com_contento3_web_widgetset_CmsadminWidgetset.__getPropMap=null;com_contento3_web_widgetset_CmsadminWidgetset.__gwtInstallCode=function(){};com_contento3_web_widgetset_CmsadminWidgetset.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==S?T:U;v.write(b+V);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==W){return typeof p.body!=W&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(Y)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(Z));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode($));g=f.createElement(_);g.language=ab;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(_);g.language=ab;g.text=c[i];e.appendChild(g);d(e,g)}}}
com_contento3_web_widgetset_CmsadminWidgetset.onScriptDownloaded=function(a){l(function(){m(a)})};r(bb,cb);var n=p.createElement(_);n.src=k;p.getElementsByTagName(db)[0].appendChild(n)}
com_contento3_web_widgetset_CmsadminWidgetset.__startLoadingFragment=function(a){return C(a)};com_contento3_web_widgetset_CmsadminWidgetset.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(_);c.language=ab;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(eb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(fb),k;if(j){j=j.replace(gb,U);if(j.indexOf(hb)>=0){continue}if(j==ib){k=i.getAttribute(jb);if(k){var l,m=k.indexOf(kb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=U}c[j]=l}}else if(j==lb){k=i.getAttribute(jb);if(k){try{d=eval(k)}catch(a){alert(mb+k+nb)}}}else if(j==ob){k=i.getAttribute(jb);if(k){try{e=eval(k)}catch(a){alert(mb+k+pb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;com_contento3_web_widgetset_CmsadminWidgetset.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(qb);if(b==-1){b=a.length}var c=a.indexOf(rb);if(c==-1){c=a.length}var d=a.lastIndexOf(sb,Math.min(c,b));return d>=0?a.substring(0,d+1):U}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(tb);b.src=a+ub;a=e(b.src)}return a}
function g(){var a=t(vb);if(a!=null){return a}return U}
function h(){var a=p.getElementsByTagName(_);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(wb)!=-1){return e(a[b].src)}}return U}
function i(){var a=p.getElementsByTagName(xb);if(a.length>0){return a[a.length-1].href}return U}
function j(){var a=p.location;return a.href==a.protocol+yb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==U){k=h()}if(k==U){k=i()}if(k==U&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_contento3_web_widgetset_CmsadminWidgetset.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[zb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Ab)!=-1}())return Ab;if(function(){return b.indexOf(Bb)!=-1}())return Cb;if(function(){return b.indexOf(Db)!=-1&&p.documentMode>=10}())return Eb;if(function(){return b.indexOf(Db)!=-1&&p.documentMode>=9}())return Fb;if(function(){return b.indexOf(Db)!=-1&&p.documentMode>=8}())return Gb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Hb;if(function(){return b.indexOf(Ib)!=-1}())return Jb;return Kb};i[zb]={gecko1_8:0,ie10:1,ie6:2,ie8:3,ie9:4,opera:5,safari:6};s=function(a,b){return b in i[a]};com_contento3_web_widgetset_CmsadminWidgetset.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};com_contento3_web_widgetset_CmsadminWidgetset.__computePropValue=k;o.__gwt_activeModules[K].bindings=com_contento3_web_widgetset_CmsadminWidgetset.__getPropMap;r(G,Lb);if(q()){return C(Mb)}var l;try{h([Eb],Nb);h([Gb],Ob);h([Cb],Pb);h([Fb],Qb);h([Jb],Rb);h([Ab],Sb);l=f[k(zb)];var m=l.indexOf(Tb);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}com_contento3_web_widgetset_CmsadminWidgetset.__softPermutationId=g;return C(l+Ub)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Vb,H);r(Vb,Wb)}
A();com_contento3_web_widgetset_CmsadminWidgetset.__moduleBase=B();u[K].moduleBase=com_contento3_web_widgetset_CmsadminWidgetset.__moduleBase;var F=D();E();r(G,Wb);z(F);return true}
com_contento3_web_widgetset_CmsadminWidgetset.succeeded=com_contento3_web_widgetset_CmsadminWidgetset();
>>>>>>> affb4fe0f5268eccc79a66ff288a603c61d8dff7
