
INSERT INTO PLATFORM_USERS.ENTITY_OPERATION VALUES (1,'ALL'); 
INSERT INTO PLATFORM_USERS.ENTITY_OPERATION VALUES (2,'VIEW');
INSERT INTO PLATFORM_USERS.ENTITY_OPERATION VALUES (3,'ADD');
INSERT INTO PLATFORM_USERS.ENTITY_OPERATION VALUES (4,'DELETE');
INSERT INTO PLATFORM_USERS.ENTITY_OPERATION VALUES (5,'EDIT');
INSERT INTO PLATFORM_USERS.ENTITY_OPERATION VALUES (6,'ASSOCIATE');
INSERT INTO PLATFORM_USERS.ENTITY_OPERATION VALUES (7,'VIEW_LISTING');

INSERT INTO PLATFORM_USERS.ENTITY VALUES (1,'GROUP');

INSERT INTO PLATFORM_USERS.PERMISSION VALUES (1,1,1);
INSERT INTO PLATFORM_USERS.PERMISSION VALUES (2,1,2);
INSERT INTO PLATFORM_USERS.PERMISSION VALUES (3,1,3);
