
CREATE TABLE PLATFORM_USERS.USER
(
USER_ID INT (11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
ENABLED BOOLEAN NOT NULL,
SALT varchar(25) NOT NULL,
ACCOUNT_ID INT (11) NOT NULL, 
CONSTRAINT FK_USR_ACCNT FOREIGN KEY (ACCOUNT_ID) REFERENCES CMS.ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE PLATFORM_USERS.GROUP
(
GROUP_ID INT (11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
GROUP_NAME VARCHAR(50) NOT NULL,
DESCRIPTION VARCHAR(50),
ACCOUNT_ID INT (11) NOT NULL,
CONSTRAINT FK_GRP_ACCNT FOREIGN KEY (ACCOUNT_ID) REFERENCES CMS.ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE PLATFORM_USERS.GROUP_MEMBER
(
ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
GROUP_ID VARCHAR(50),
USER_ID VARCHAR(50),
CONSTRAINT UNIQUE KEY UK_GROUP_MEMBERS (USER_ID, GROUP_ID),
CONSTRAINT FK_USR_ACCNT FOREIGN KEY (USER_ID) REFERENCES PLATFORM_USERS.USER(USER_ID),
CONSTRAINT FK_GRP_ACCNT FOREIGN KEY (GROUP_ID) REFERENCES PLATFORM_USERS.GROUP(GROUP_ID)
);

CREATE TABLE PLATFORM_USERS.ROLE
(
ROLE_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
ROLE_NAME VARCHAR(50) NOT NULL,
DESCRIPTION VARCHAR (500),
ACCOUNT_ID INT(11) NOT NULL, 
CONSTRAINT FK_ROLE_ACCNT FOREIGN KEY (ACCOUNT_ID) REFERENCES CMS.ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE PLATFORM_USERS.GROUP_ROLE
(
ID INT (11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
GROUP_ID INT (11) NOT NULL,  
ROLE_ID INT (11) NOT NULL,
CONSTRAINT UNIQUE KEY UK_GROUP_ROLE (GROUP_ID, ROLE_ID),
CONSTRAINT FK_GRP_GRPROLE FOREIGN KEY (GROUP_ID) REFERENCES PLATFORM_USERS.GROUP(GROUP_ID),
CONSTRAINT FK_ROLE_GRPROLE FOREIGN KEY (ROLE_ID) REFERENCES PLATFORM_USERS.ROLE(ROLE_ID)
);

CREATE TABLE PLATFORM_USERS.ENTITY
(
ENTITY_ID INT (11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
ENTITY_NAME VARCHAR (50) NOT NULL
);

CREATE TABLE PLATFORM_USERS.ENTITY_OPERATION
(
ENTITY_OPERATION_ID INT (11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
ENTITY_OPERATION_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PLATFORM_USERS.PERMISSION
(
PERMISSION_ID INT (11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
ENTITY_ID INT (11) NOT NULL,
ENTITY_OPERATION_ID INT(11) NOT NULL,
CONSTRAINT UNIQUE KEY UK_ROLE_PERMISSION (ENTITY_ID, ENTITY_OPERATION_ID),
CONSTRAINT FK_PERMISSION_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES PLATFORM_USERS.ENTITY(ENTITY_ID),
CONSTRAINT FK_PERMISSION_ENTITYOPERATION FOREIGN KEY (ENTITY_OPERATION_ID) REFERENCES PLATFORM_USERS.ENTITY_OPERATION(ENTITY_OPERATION_ID)
);

CREATE TABLE PLATFORM_USERS.ROLE_PERMISSION
(
ID INT (11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
ROLE_ID INT (11) NOT NULL,
PERMISSION_ID INT (11) NOT NULL,
CONSTRAINT UNIQUE KEY UK_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID),
CONSTRAINT FK_ROLEPERMISSION_ROLE FOREIGN KEY (ROLE_ID) REFERENCES PLATFORM_USERS.ROLE(ROLE_ID),
CONSTRAINT FK_ROLEPERMISSION_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PLATFORM_USERS.PERMISSION(PERMISSION_ID)
);
